function [DiffusionMatrix] = DiffusionMatrixGen(msh,D,lambda)
%Function to derive the Global Matrix from Diffusion and Reaction local 
%element matrices. Takes the following inputs:
%msh - The 1D mesh as generated by OneDimLinearMeshGen.m
%D - The Diffusion co-efficient
%lambda - The linear reaction co-efficient.

%Initiate a matrix of the appropiate size.
matrix = zeros(msh.ngn);
    
%This for loop iterates through the established matrix, cumulatively 
%adding the 2*2 local element matrices as appropiate.
for i = 1:msh.ngn-1
    matrix(i:i+1,i:i+1) = matrix(i:i+1,i:i+1)...
                          +LaplaceElemMatrix(D,i,msh)...
                          -LinearReactionMatrix(lambda,i,msh);
end
DiffusionMatrix = matrix;
end