function [localElementMatrix] = LaplaceElemMatrix(D,eID,msh)
%Returns the 2*2 Diffusion local element matrix for a given
%element. D is the Diffusion coefficient, eID is the element index
%(largely redundant), and msh is the mesh as generated by 
%OneDimLinearMeshGen.m

MatrixElement = 0.5 * D/msh.elem(eID).J; %Get J

localElementMatrix = [MatrixElement, -MatrixElement;...
                      -MatrixElement, MatrixElement];
end

