function [localElementMatrix] = LinearReactionMatrix(lambda,eID,msh)
%Returns the 2*2 linear reaction local element matrix for a given
%element. D is the Diffusion coefficient, eID is the element index
%(largely redundant), and msh is the mesh as generated by
%OneDimLinearMeshGen.m
if lambda == 0
    localElementMatrix = zeros(2);
else   
    MatrixElement = (lambda*msh.elem(eID).J)/3;%Get J and multiply common terms
    
    localElementMatrix = [2*MatrixElement,MatrixElement;...
        MatrixElement, 2*MatrixElement];
end
end