function [SourceVector] = SourceVectorGen(msh,f)
%GLOBALVECTOR Function for deriving the Global Source Vector when f is a
%constant. Inputs are msh, (the 1D linear mesh as generated by 
%OneDimLinearMeshGen.m) and f, the source coefficient.

%Initialise a vector of the appropiate size
vector = zeros(1,msh.ngn);
%Iterate through the vector, adding the local element vector at each index.
for i = 1:msh.ngn-1
   vector(i:i+1) =  vector(i:i+1) + [f*msh.elem(i).J,f*msh.elem(i).J];
end
%Transpose the vector and return it.
SourceVector = vector';
end